apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fintechy-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: fintechy-microservices/api-gateway
        ports:
        - containerPort: 8070
        env:
            - name: PORT
              value: "8070"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: fintechy-microservices-dev
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 8070
      targetPort: 8070